In [2]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

1. 전체 문서에 대해 고유한 토큰(token), ex) 어휘 사전(vocabulary) 만든다.
2. 특정 문서에 각 단어가 얼마나 자주 등장하는지 헤아려 문서의 특성 벡터를 만든다.

각 문서에 있는 고유한 단어는 BoW 어휘 사전에 잇는 모든 단어의 일부분에 지나지 않으므로 특성 벡터는 대부분이 0으로 채워진다. 

그래서 이 특성 벡터를 회소(sparse)라한다. 

BoW는 각 단어가 등장한 횟수를 수치화하는 텍스트 표현 방법이기 때문에, 주로 어떤 단어가 얼마나 등장했는지를 기준으로 문서가 어떤 성격의 문서인지를 판단하는 작업에 쓰입니다. 즉, 분류 문제나 여러 문서 간의 유사도를 구하는 문제에 주로 쓰입니다. 가령, '달리기', '체력', '근력'과 같은 단어가 자주 등장하면 해당 문서를 체육 관련 문서로 분류할 수 있을 것이며, '미분', '방정식', '부등식'과 같은 단어가 자주 등장한다면 수학 관련 문서로 분류할 수 있습니다.

In [3]:
count=CountVectorizer()

In [4]:
docs=np.array([
    'The sun is shining',
    'The weather is sweet',
    'The sun is shining, the weater is sweet, and one and is two'
])

In [6]:
bag=count.fit_transform(docs)

In [7]:
print(count.vocabulary_)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 9, 'sweet': 5, 'weater': 8, 'and': 0, 'one': 2, 'two': 7}


어휘 사전은 고유 단어와 정수 인덱스가 매핑된 파이썬 딕셔너리에 저장되어있다.

In [12]:
print(bag.toarray())# 특성 벡터 출력

[[0 1 0 1 1 0 1 0 0 0]
 [0 1 0 0 0 1 1 0 0 1]
 [2 3 1 1 1 1 2 1 1 0]]


특성 벡터의 각 인덱스는 CountVectorizer 의 어휘 사전 딕셔너리에 저장된 정수 값에 해당된다.

특성 벡터의 단어빈도(Term frequency)라고한다  

문서 d에 등장한 단어 t의 횟수는 tf(f,d)처럼 쓴다.

In [21]:
from sklearn.feature_extraction.text import TfidfTransformer

In [59]:
tfidf=TfidfTransformer(use_idf=True,
                       norm='l2',
                       smooth_idf=True)

In [60]:
np.set_printoptions(precision=2)

In [61]:
print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[0.   0.43 0.   0.56 0.56 0.   0.43 0.   0.   0.  ]
 [0.   0.39 0.   0.   0.   0.5  0.39 0.   0.   0.66]
 [0.55 0.49 0.27 0.21 0.21 0.21 0.32 0.27 0.27 0.  ]]


In [62]:
import re